branches/grappelli_2/urls.py
# coding: utf-8

from django.conf.urls.defaults import *

urlpatterns = patterns('',
    
    # BOOKMARKS
    url(r'^bookmark/add/$', 'grappelli.views.bookmarks.add_bookmark', name="grp_bookmark_add"),
    url(r'^bookmark/remove/$', 'grappelli.views.bookmarks.remove_bookmark', name="grp_bookmark_remove"),
    url(r'^bookmark/get/$', 'grappelli.views.bookmarks.get_bookmark', name="grp_bookmark_get"),
    
    # HELP
    url(r'^help/(?P<object_id>\d+)/$', 'grappelli.views.help.detail', name="grp_help_detail"),
    url(r'^help', 'grappelli.views.help.help', name="grp_help"),
    
    # GENERIC
    url(r'^obj_lookup/$', 'grappelli.views.generic.generic_lookup', name="grp_generic_lookup"),
    
    # FOREIGNKEY LOOKUP
    url(r'^related_lookup/$', 'grappelli.views.related.related_lookup', name="grp_related_lookup"),
    url(r'^m2m_lookup/$', 'grappelli.views.related.m2m_lookup', name="grp_m2m_lookup")
    
    # AUTOCOMPLETE LOOKUP
    #url(r'^autocomplete_lookup/$', 'grappelli.views.related.autocomplete_lookup', name="grp_autocomplete_lookup"),
    #url(r'^autocomplete_lookup_id/$', 'grappelli.views.related.autocomplete_lookup_id', name="grp_autocomplete_lookup_id"),
    
    # M2M AUTOCOMPLETE LOOKUP
    #url(r'^m2m_autocomplete_lookup/$', 'grappelli.views.related.m2m_autocomplete_lookup', name="grp_m2m_autocomplete_lookup"),
    #url(r'^m2m_autocomplete_lookup_id/$', 'grappelli.views.related.m2m_autocomplete_lookup_id', name="grp_m2m_autocomplete_lookup_id"),
    
)

branches/grappelli_2/models/help.py
# coding: utf-8

from django.db import models, transaction
from django.utils.translation import ugettext as _

from grappelli.fields import PositionField

class Help(models.Model):
    """
    Help Entry.
    """
    
    title = models.CharField(_('Title'), max_length=50)
    
    # order
    order = PositionField(_('Order'))
    
    class Meta:
        app_label = "grappelli"
        verbose_name = _('Help')
        verbose_name_plural = _('Help')
        ordering = ['order']
    
    def __unicode__(self):
        return u"%s" % (self.title)
    
    save = transaction.commit_on_success(models.Model.save)
    

class HelpItem(models.Model):
    """
    Help Entry Item.
    """
    
    help = models.ForeignKey(Help, verbose_name=_('Help'))
    title = models.CharField(_('Title'), max_length=200)
    link = models.CharField(_('Link'), max_length=200, help_text=_('The Link should be relative, e.g. /admin/blog/.'))
    body = models.TextField(_('Body'))
    
    # order
    order = PositionField(_('Order'), unique_for_field='help')
    
    class Meta:
        app_label = "grappelli"
        verbose_name = _('Help Entry')
        verbose_name_plural = _('Help Entries')
        ordering = ['help', 'order']
    
    def __unicode__(self):
        return u"%s" % (self.title)
    
    def get_body(self):
        body = self.body.replace('<h2>', '</div><div class="module"><h2>')
        return body
    
    save = transaction.commit_on_success(models.Model.save)
    

branches/grappelli_2/views/help.py
# coding: utf-8

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.shortcuts import get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.translation import ugettext as _

from grappelli.models.help import Help, HelpItem

def detail(request, object_id):
    """
    CMS Help (Detail).
    """
    
    obj = get_object_or_404(HelpItem, pk=object_id)
    menu = Help.objects.filter(helpitem__isnull=False).distinct()
    
    return render_to_response('grappelli/help/help_detail.html', {
        'object': obj,
        'menu': menu,
        'title': obj.title,
    }, context_instance=RequestContext(request) )
detail = staff_member_required(detail)

def help(request):
    """
    CMS Help (Overview).
    """
    
    menu = Help.objects.filter(helpitem__isnull=False).distinct()
    
    return render_to_response('grappelli/help/help.html', {
        'menu': menu,
        'title': _('Help'),
    }, context_instance=RequestContext(request) )
help = staff_member_required(help)

branches/grappelli_2/templates/grappelli/help/help.html
{% extends "admin/base_site.html" %}
{% load adminmedia %}
{% load i18n %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/documentation.css" />
{% endblock %}{% block coltype %}colSM{% endblock %}
{% block bodyclass %}dashboard documentation{% endblock %}
{% block breadcrumbs %}<div class="breadcrumbs"><a href="/admin/">{% trans "Home" %}</a> &rsaquo; {% trans "Help" %}</div>{% endblock %}

{% block content %}
<div id="content-main" class="rte">
    <div class="module">
        <p>{% trans "This section should explain the handling of the Admin-Interface/CMS. Permissions provided, you can change/add entries to this Section." %}</p>
    </div>
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related" style="float: left !important;">
    {% for help in menu %}
    <div class="module">
        <table>
            <caption style="width:100%;">{{ help }}</caption>
            {% for helpitem in help.helpitem_set.all %}
            <tr class="collapse">
                <th scope="row"><a href="{{ helpitem.id }}/">{{ helpitem }}</a></th>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% endfor %}
</div>
{% endblock %}

branches/grappelli_2/templates/grappelli/help/help_detail.html
{% extends "admin/base_site.html" %}
{% load adminmedia %}
{% load i18n %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}css/documentation.css" />
{% endblock %}
{% block extrahead %}
<script>
$(document).ready(function(){
    // Sync Active Help Entry With Link In Sidebar
    $('body').each(function(){
        var ActiveItem = $('.module').attr('name');
        $('#content-related').find('a.'+ActiveItem).addClass('selected');
    });
});
</script>
{% endblock %}
{% block coltype %}colSM{% endblock %}
{% block bodyclass %}dashboard documentation{% endblock %}
{% block breadcrumbs %}<div class="breadcrumbs"><a href="/admin/">{% trans "Home" %}</a> &rsaquo; <a href="/grappelli/help/">{% trans "Help" %}</a> &rsaquo; {{ object.title }}</div>{% endblock %}

{% block content %}
<div id="content-main" class="rte">
    <div class="module" name="detail-{{ object.id }}">
    {{ object.get_body|safe }}
    </div>
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    {% for help in menu %}
    <div class="module">
        <table>
            <caption style="width:100%;">{{ help }}</caption>
            {% for helpitem in help.helpitem_set.all %}
            <tr class="collapse">
                <th scope="row"><a href="../{{ helpitem.id }}/" class="detail-{{ helpitem.id }}">{{ helpitem }}</a></th>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% endfor %}
</div>
{% endblock %}